# Generated by Django 5.0.4 on 2026-05-12 11:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código del dispositivo')),
                ('ip', models.CharField(max_length=50, validators=[django.core.validators.validate_ipv4_address], verbose_name='Dirección IP')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'db_table': 'dispositivo',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres completos')),
                ('correo', models.EmailField(max_length=150, unique=True, verbose_name='Correo electrónico')),
                ('codigo_docente', models.CharField(max_length=10, unique=True, verbose_name='Código de docente')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fingerprint', models.IntegerField(unique=True, verbose_name='ID de huella digital')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'db_table': 'docente',
                'ordering': ['nombres'],
            },
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del laboratorio')),
                ('ubicacion', models.CharField(max_length=50, verbose_name='Ubicación')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispositivo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laboratorio', to='api.dispositivo', verbose_name='Dispositivo asociado')),
            ],
            options={
                'verbose_name': 'Laboratorio',
                'verbose_name_plural': 'Laboratorios',
                'db_table': 'laboratorio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=15, verbose_name='Día de la semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='api.docente', verbose_name='Docente')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='api.laboratorio', verbose_name='Laboratorio')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'db_table': 'horario',
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('docente', 'laboratorio', 'dia_semana', 'hora_inicio')},
            },
        ),
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('acceso_permitido', models.BooleanField(verbose_name='Acceso permitido')),
                ('motivo', models.CharField(blank=True, max_length=200, verbose_name='Motivo')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_acceso', to='api.docente', verbose_name='Docente')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_acceso', to='api.laboratorio', verbose_name='Laboratorio')),
            ],
            options={
                'verbose_name': 'Registro de Acceso',
                'verbose_name_plural': 'Registros de Acceso',
                'db_table': 'registro_acceso',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['-fecha_hora'], name='registro_ac_fecha_h_042084_idx'), models.Index(fields=['acceso_permitido'], name='registro_ac_acceso__224621_idx')],
            },
        ),
    ]
